modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="ZareMate"
description='''Server-side utility commands for FTB Teams.'''

[[dependencies.ftb_teams_util]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.ftb_teams_util]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="SERVER"

[[dependencies.ftb_teams_util]]
modId="ftbteams"
type="required"
versionRange="[${ftb_teams_version},)"
ordering="AFTER"
side="SERVER"
